export const expenseData = [
  {
    color: "A52A2A",
    icon: "https://xtrack-main.onrender.com/assets/food.svg",
    category: "Food and Drinks",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "FFBF00",
    icon: "https://xtrack-main.onrender.com/assets/entertainment.svg",
    category: "Entertainment",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "FF00FF",
    icon: "https://xtrack-main.onrender.com/assets/shopping.svg",
    category: "Shopping",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "007FFF",
    icon: "https://xtrack-main.onrender.com/assets/bills.svg",
    category: "Bills and Fees",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "177245",
    icon: "https://xtrack-main.onrender.com/assets/rent.svg",
    category: "Rent",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "E97451",
    icon: "https://xtrack-main.onrender.com/assets/transportation.svg",
    category: "Transportation",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "DE3163",
    icon: "https://xtrack-main.onrender.com/assets/car.svg",
    category: "Car",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "CD5700",
    icon: "https://xtrack-main.onrender.com/assets/travel.svg",
    category: "Travel",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "8A2BE2",
    icon: "https://xtrack-main.onrender.com/assets/grocery.svg",
    category: "Grocery",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "FF4F00",
    icon: "https://xtrack-main.onrender.com/assets/sports.svg",
    category: "Sports and Hobbies",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "100C08",
    icon: "https://xtrack-main.onrender.com/assets/health.svg",
    category: "Healthcare",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "808000",
    icon: "https://xtrack-main.onrender.com/assets/education.svg",
    category: "Education",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "FF69B4",
    icon: "https://xtrack-main.onrender.com/assets/beauty.svg",
    category: "Beauty",
    transactionCount: 0,
    type: "Expenses",
  },
  {
    color: "00CCCC",
    icon: "https://xtrack-main.onrender.com/assets/family.svg",
    category: "Family and Friends",
    transactionCount: 0,
    type: "Expenses",
  },
];
